version: '3'
services:
  app:
    build: .
    command: yarn start
    restart: always
    container_name: web2_w3_todoapp
    networks:
      - web
    environment:
      - REDIS_URL=redis://redisdb:6379
      - POSTGRES_URL=postgres://postgres:e7105564@postgresdb:5432/web2-week3
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:web2-week3.phamdung.me"
      - "traefik.docker.network=web"
      - "traefik.port=8989"
    volumes:
      - "../app/:/app/"
    
networks:
  web:
    external: true
